= Terraform CLI

Finally, I would like to give a short introduction on how to use Terraform CLI. Essentially, only three steps are necessary: initialize, plan and apply.

== Initialize

`terraform init` has to be started before the actual execution.

In the first step, Terraform installs modules into the local directory. The local backend is then initialized -- there are numerous cloud-based backends. Next, Terraform uploads providers from the registry `https://registry.terraform.io/` to the local directory. Finally, a _lock_ file `.terraform.lock.hcl` containing provider meta information is created.

If necessary, the configuration can be checked with a `terraform validate`.

== Plan

To preview what changes Terraform will make, the CLI provides the `plan` command. The plan can be redirected to a file in binary form: `terraform plan -out myplan`. A readable _JSON_ output of the created plan can be obtained with `terraform show -json myplan`. This step is optional -- the changes will also be output with the `apply` command. Essentially, this is a "dry run".

== Apply

The configuration can now be applied. The `apply` command is available for this.

`terraform apply myplan` displays the change plan and asks the developer to confirm the changes with "yes". Other user inputs abort the operation.

[source,json]
----
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
  + create

Terraform will perform the following actions:

  # docker_container.nginx will be created
  + resource "docker_container" "nginx" {

      ...

      + name             = "nginx-demo"
      
      ...

      + healthcheck {
          + interval     = (known after apply)
          + retries      = (known after apply)
          + start_period = (known after apply)
          + test         = (known after apply)
          + timeout      = (known after apply)
        }

      + labels {
          + label = (known after apply)
          + value = (known after apply)
        }
    }

  # docker_image.nginx will be created
  + resource "docker_image" "nginx" {
      + id          = (known after apply)
      + latest      = (known after apply)
      + name        = "nginx:1.21.6-alpine"
      + output      = (known after apply)
      + repo_digest = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + nginx_image = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
----

== Destroy

Existing infrastructure can also be destroyed again:

`terraform destroy`

Terraform displays what is being destroyed and, just like `apply`, prompts you to confirm this step with a "yes".

[source,json]
----
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
  - destroy

Terraform will perform the following actions:

  # docker_container.nginx will be destroyed
  - resource "docker_container" "nginx" {
      - attach            = false -> null
      - command           = [
          - "nginx",
          - "-g",
          - "daemon off;",
        ] -> null

      ...

      - entrypoint        = [
          - "/docker-entrypoint.sh",
        ] -> null
      - env               = [] -> null
      - gateway           = "172.17.0.1" -> null
      - group_add         = [] -> null
      - hostname          = "be3fbc6581db" -> null
      - id                = "be3fbc6581db..." -> null
      - image             = "sha256:674e6760e55a..." -> null

      ...

      - name              = "nginx-demo" -> null
      - network_data      = [
          - {
              - gateway                   = "172.17.0.1"
              - global_ipv6_address       = ""
              - global_ipv6_prefix_length = 0
              - ip_address                = "172.17.0.2"
              - ip_prefix_length          = 16
              - ipv6_gateway              = ""
              - network_name              = "bridge"
            },
        ] -> null

       ...
    }

  # docker_image.nginx will be destroyed
  - resource "docker_image" "nginx" {
      - id          = "sha256:674e6760e55a...nginx:1.21.6-alpine" -> null
      - latest      = "sha256:674e6760e55a..." -> null
      - name        = "nginx:1.21.6-alpine" -> null
      - repo_digest = "nginx@sha256:5a0df7fb7c8c..." -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.

Changes to Outputs:
  - nginx_image = "nginx:1.21.6-alpine (nginx@sha256:5a0df7fb7c8c...)" -> null

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value:
----