= Terraform basics

Ein Terraform Script besteht aus nur wenigen Elementen. Diese sind recht schnell zu erlernen. Auch die Syntax, die der von _JSON_ sehr ähnelt ist nicht schwierig.

Im wesentlichen ist ein funktionsfähiges Script aus nur zwei Elementen aufgebaut: einem oder mehreren _Providern_ und den _Resourcen_. Kompliziertere Scripte beinhalten _Data_ und andere Elemente. Um eine aussagekräftigere Ausgabe zu erhalten gibt es _Output_. Um ein Terraform Script frei von hard-coded Werten zu halten, bietet sich das Element _Variable_.

Im folgenden werde ich kurz die o.g. Elemente -- das sind die wichtigsten -- vorstellen. Mit dem dann gesammelten Wissen stelle ich im darauffolgenden Absatz ein komplexeres Beispiele vor, dass eine Cloud-Infrastruktur konfiguriert.

== HCL

Zu allererst jedoch eine sehr kurze Einführung in die *HashiCorp Configuration Language*. Wie eingangs gesagt, ist die Sprache eng mit _JSON_ verwandt. Genauso gut ließe sich ein Terraform Script auch mit _JSON_ schreiben, wenngleich der Aufwand höher ist.
Ein Block innerhalb eines Scripts besteht aus einem Header und einem Body. Der Haeder ist folgendermaßen aufgebaut:

```
<BLOCK TYPE> "<BLOCK LABEL>" "<BLOCK LABEL>"
```

Dabei bezeichnet der `BLOCK TYPE` z.B. einen Provider oder eine Resource.

Der Body ist beinahe gleich aufgebaut wie bei _JSON_. Anders als bei _JSON_ verwendet _HCL_ keinen Doppelpunkt sondern ein Gleichheitszeichen für die Zuweisung.

```
<IDENTIFIER> = <EXPRESSION>
```

Ein valides HCL-Beispiel ist:

```json
resource "foo" "bar" {
    id = 123
}
```

[TIP]
====
Verschachtelte Blöcke lassen sich in _HCL_ wesentlich kompakter schreiben als mit _JSON_, wie wir gleich anhand eines Beispieles sehen werden.
====

== Provider

Ein Terraform Script muss angeben, welche Provider es benötigt. Ein Provider kann man sich wie eine API vorstellen. Ohne Provider kann Terraform keinerlei Infrastruktur verwalten. Provider interagieren also mit einer Cloud- oder On-Premise Infrastruktur. Die Konfiguration eines Providers muss im _root_ Verzeichnis stehen. Auch die benötigten Provider und die Version muss sich dort befinden. Hier ein kurzes und unvollständiges Beispiel

```json
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = ">= 2.16.0"
    }
  }
}

...

provider "docker" {
}
```

Das Script fordert an, dass der Provider _docker_ in mindestens der Version `2.16.0` benötigt wird. Der Provider selbst ist nicht näher konfiguriert.

== Resource

Resourcen beschreiben Objekte einer Infrastruktur und sind somit die wichtigsten Elemente innerhaln eines Scripts. Jede Resource wird von einem Provider implementiert und stellt, je nach Typ, eine Vielzahl von Einstellungsmöglichkeiten bereit. In Terraform gibt es eine Reihe von Meta-Argumenten, etwa `depends_on` um explizit anzugeben, welche Resource von einer anderen abhängt. Dies ist nicht unbedingt erforderlich, da Terraform selständig Abhängigkeiten auflöst, kann aber zu einem besseren Verständnis bzw. Überblick bei größeren Scripten führen.

[source,json]
----
resource "docker_image" "nginx" { // <1>
  name = "nginx:1.21.6-alpine" // <2>
}

resource "docker_container" "nginx" { // <1>
  image = docker_image.nginx.repo_digest // <3>
  name  = "nginx-demo" // <4>
}
----
<1> Resourcen `docker_image` und `docker_container` des Providers `docker` (siehe vorheriges Beispiel in <<Provider>>)
<2> Festlegen des Images `nginx` in der Version `1.21.6-alpine`
<3> Referenzieren des Docker Images durch `repo_digest`, anhand des sha256 digest, siehe Terraform Dokumentation footnote:[https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/image]
<4> Der Name des Containers ist "nginx-demo" 

== Data

Provider können zusätzlich zu Resourcen auch _Data Sources_ zur Verfügung stellen. _Data Sources_ stellen Informationen außerhalb von Terraform bereit und entsprechen gewissermaßen Daten einer Resource der Infrastruktur. Beispielsweise lassen sich damit für Kubernetes alle verfügbaren Namespaces eines Clusters ausgeben.

```json
data "kubernetes_all_namespaces" "allns" {
}
```

== Output

Unter _Output_ kann man sich die von Programmsprachen bekannten Rückgabewerte vorstellen. Diese dienen zur verständlicheren Ausgabe im Terminal oder stellen Informationen für andere Terraform Scripts zur Verfügung.

[source,json]
----
output "top_secret" {
  value     = "do not tell the guys"
  sensitive = true // <1>
}
----
<1> Sensible Daten wie Passwörter oder API Schlüssel lassen durch _Output_ Elemente maskieren.

[TIP]
====
Best practise ist die _Output_ Blöcke in einer gesonderten Datei `outputs.tf` abzulegen.
====

== Variables

Eine Variable (auch _Input Variable_) ermöglicht es, Terraform Scripts anzupassen ohne den Quellcode (also das Script selbst) zu modifizieren. Auch verhindert man dadurch, mit hardcoded Variablen zu arbeiten. Eine Terraform Variable gleicht in Programmiersprachen anders als man vermutet eher einer Konstanten. Standardmäßig werden Variablen in einer `variables.tf` Datei abgelegt.

[source,json]
----
variable "homer" {
  type = string // <1>
  description = "Homer's DOH!" // <2>
  sensitive = false // <3>
  nullable = false // <4>
  default = "oh no, DOH!" // <5>
}
----
<1> Es ist nicht erforderlich einen Typ anzugeben, jedoch bewährt es sich in der Praxis, da beim Lesen der Konfiguration keine Annahmen getroffen werden müssen. Auch quitiert Terraform mit einer besseren Fehlermeldung, falls der Typ der Variablen nicht korrekt ist. Eine Variable kann vom folgenden Typ sein:
* string
* number
* bool
* list(_<TYPE>_)
* set(_<TYPE>_)
* map(_<TYPE>_)
* tuple([_<TYPE>_, _<TYPE>_, ...])
* object({_<ATTRIBUTE NAME>_ = _<TYPE>_})
<2> Eine aussagekräftige Beschreibung ist nie verkehrt und es ist Best-Practise, um auch anderen Mitwirkenden wissen zu lassen, um was es hier geht.
<3> `sensitive` sagt aus, ob bei der Eingabe eines Wertes, dieser maskiert werden soll.
<4> `nullable`, wie der Name schon sagt, legt fest, ob ein Wert auch fehlen darf.
<5> `default` ist nicht unbedingt erforderlich. Allerdings wird der Entwickler beim Ausführen des Scripts jedes Mal aufgefordert für _doh_ einen Wert anzugeben. Möchte man keinen Standardwert hier setzen, muss eine Datei angelegt werden.

[source,text]
.terraform.tfvars
----
homer="oh no, DOH!"
----

Außerdem können Eingaben seitens eines Entwicklers validiert werden. Es gibt eine Vielzahl an Funktionen footnote:[https://www.terraform.io/language/values/variables] die für die Validierung verwendet werden können.

[NOTE]
====
Um Variablen zu referenzieren, stellt man ein `var` vor dem Variablennamen voran -- nicht `vars` oder `variable` wie man vielleicht annehmen möchte. In unserem Fall sieht das dann so aus: `var.doh`
====

=== Local Values
Last but not least gibt es noch sog. _Local Values_. Mehr Informationen dazu kann man in der Terraform Dokumentation footnote:[https://www.terraform.io/language/values/locals] nachlesen.

== Let's put everything together...

Wir setzen nun alle Teile des Beispiels zusammen. Der Haupteinstiegspunkt für Terraform ist die Datei `main.tf`. Sie entält die Definitionen für Provider und Resourcen.

In `variables.tf` ist eine Variable für den Namen des Images für Docker hinterlegt. Der Default-Wert ist hier mit angegeben, kann aber wie weiter oben schon gesagt, auch weggelassen werden. In diesem Fall müsste der Entwickler jedes Mal das Image angeben.

Für die Ausgabe habe ich eine Kombination aus dem Namen des Images und dessen Digest definiert. Wenngleich etwas künstlich anmutend möchte ich damit die Mächtigkeit von _Output_ zeigen.

[source,json]
.main.tf
----
include::./resource/main.tf[]
----
Die Hauptdatei enthält die Provider und Resource Blöcke.

[source,json]
.variables.tf
----
include::./resource/variables.tf[]
----
Der Image Name für Docker ist hier mit einem Default Wert hinterlegt.

[source,json]
.outputs.tf
----
include::./resource/outputs.tf[]
----
Mithilfe von Outputs lassen sich zugeschnittene Ausgaben definieren, womit auch die Lesbarkeit bei größeren Scripts erhöht wird.