= Infrastructure as Code

Eines der vielfach genannten Buzzwords der letzten Jahren ist _IaC_ (Infrastructure as Code). Damit lässt sich eine virtuelle Infrastruktur mit einem deklarativen Model in Textdateien definieren. Diese Textdateien lassen sich genauso wie Quellcode in Repositories, z.B. GitHub oder GitLab, ablegen und sind damit automatisch versioniert. Dadurch kann der Entwickler nachvollziehen, wie sich die Infrastruktur im Laufe der Zeit verändert hat und ob sich eventuell Fehler eingeschlichen haben. Der Code dient also auch als Dokumentation. Eine, wie in der Vergangenheit notwendige Intranet-Dokumentation ist damit weitestgehend nicht mehr unbedingt erforderlich. Auch andere Vorteile wie das gleichzeitige Arbeiten an der Infrastruktur ist damit einfacher möglich, wenngleich ein Testen der Änderungen natürlich weiterhin notwendig ist.

include::./declarative.adoc[leveloffset=+1]

include::./state_management.adoc[leveloffset=+1]

include::./mutability.adoc[leveloffset=+1]

include::./provisioning.adoc[leveloffset=+1]